version: "3.1"
services:
  web:
    build: .
    container_name: node_web
    env_file:
      .env
    depends_on:
      - db
    ports:
      - "80:3000"
      - "9229:9229"
  db:
    image: mysql
    container_name: node_mysql
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      .env
    volumes:
      - ./tmp/db:/var/lib/mysql
