version: "3.1"
services:
  node:
    build: node
    container_name: node_web
    env_file:
      node/.env
    depends_on:
      - mysql
    ports:
      - "3000:3000"
      - "5000:5000"
    volumes:
      - ./node:/home/app
    networks:
      - frontend
      - backend
  mysql:
    build: mysql
    container_name: node_mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    env_file:
      mysql/.env
    volumes:
      - ./mysql/db:/var/lib/mysql
    networks:
      - backend
networks:
  frontend:
  backend:
    internal: true
